// <auto-generated />
using System;
using API_Service.AppData.DataService;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Service.Migrations
{
    [DbContext(typeof(AuthenticationDbContext))]
    [Migration("20260614152824_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataContext.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LoggedInAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Accounts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("48e283eb-8193-4de0-a025-e8dcb6bc678a"),
                            CreatedAt = new DateTime(2025, 4, 10, 10, 15, 30, 0, DateTimeKind.Unspecified),
                            Password = "TestJohn@1994",
                            UserId = new Guid("1e61f4a4-0e98-4fd9-bfc4-0c1c0da4a66e")
                        },
                        new
                        {
                            Id = new Guid("50b26a44-c7f9-462a-9d4f-c66ac2e9938e"),
                            CreatedAt = new DateTime(2025, 5, 10, 10, 15, 30, 0, DateTimeKind.Unspecified),
                            Password = "TestJane@1994",
                            UserId = new Guid("4b79aeeb-96cd-49bf-abf0-8b5f6f693467")
                        });
                });

            modelBuilder.Entity("DataContext.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool?>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1e61f4a4-0e98-4fd9-bfc4-0c1c0da4a66e"),
                            Email = "doe.john@gmail.com",
                            IsVerified = true,
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = new Guid("4b79aeeb-96cd-49bf-abf0-8b5f6f693467"),
                            Email = "doe.jane@gmail.com",
                            IsVerified = true,
                            Name = "Jane Doe"
                        });
                });

            modelBuilder.Entity("DataContext.Models.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("1e61f4a4-0e98-4fd9-bfc4-0c1c0da4a66e"),
                            Role = 2
                        },
                        new
                        {
                            UserId = new Guid("4b79aeeb-96cd-49bf-abf0-8b5f6f693467"),
                            Role = 1
                        });
                });

            modelBuilder.Entity("DataContext.Models.Account", b =>
                {
                    b.HasOne("DataContext.Models.User", null)
                        .WithOne()
                        .HasForeignKey("DataContext.Models.Account", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataContext.Models.UserRole", b =>
                {
                    b.HasOne("DataContext.Models.User", null)
                        .WithOne()
                        .HasForeignKey("DataContext.Models.UserRole", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
